import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#06080D',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingTop: 62,
    paddingHorizontal: 20,
    paddingBottom: 140,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 20,
  },
  avatarWrap: {
    width: 34,
    height: 34,
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  avatar: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: '#FFD9A6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  onlineDot: {
    position: 'absolute',
    right: 1,
    bottom: 2,
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#2BE26E',
    borderWidth: 1,
    borderColor: '#06080D',
  },
  title: {
    flex: 1,
    color: '#E8EDF6',
    fontSize: 33,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#E2E8F4',
    fontSize: 30,
    fontWeight: '700',
    marginRight: 12,
  },
  sectionLine: {
    flex: 1,
    height: 1,
    backgroundColor: '#283141',
  },
  summaryRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 18,
  },
  summaryCard: {
    width: '32%',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#232B3A',
    backgroundColor: '#171C25',
    paddingHorizontal: 10,
    paddingVertical: 12,
  },
  summaryLabel: {
    marginTop: 8,
    color: '#919BAB',
    fontSize: 9,
    fontWeight: '700',
    letterSpacing: 0.8,
  },
  summaryValue: {
    marginTop: 4,
    color: '#F0F4FB',
    fontSize: 30,
    fontWeight: '700',
  },
  chartCard: {
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#202838',
    backgroundColor: '#141922',
    padding: 14,
    marginBottom: 18,
  },
  chartHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 12,
  },
  chartTitle: {
    color: '#E9EEF9',
    fontSize: 15,
    fontWeight: '600',
  },
  chartBadge: {
    height: 26,
    borderRadius: 14,
    paddingHorizontal: 10,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(43, 226, 110, 0.2)',
  },
  chartBadgeText: {
    color: '#2BE26E',
    fontSize: 11,
    fontWeight: '700',
  },
  chartArea: {
    height: 140,
    borderRadius: 12,
    backgroundColor: '#151A23',
    overflow: 'hidden',
    justifyContent: 'flex-end',
    paddingHorizontal: 10,
    paddingBottom: 12,
  },
  chartBar: {
    position: 'absolute',
    bottom: 12,
    width: 46,
    borderRadius: 8,
    backgroundColor: '#343A45',
  },
  barOne: {
    left: 10,
    height: 34,
  },
  barTwo: {
    left: 58,
    height: 48,
  },
  barThree: {
    left: 106,
    height: 76,
  },
  barFour: {
    left: 154,
    height: 96,
    backgroundColor: '#33E66F',
  },
  barFive: {
    left: 202,
    height: 70,
  },
  chartCurve: {
    position: 'absolute',
    left: 26,
    right: 34,
    bottom: 42,
    height: 64,
    borderTopWidth: 3,
    borderTopColor: '#33E66F',
    borderRadius: 44,
    transform: [{ rotate: '12deg' }],
  },
  chartGlow: {
    position: 'absolute',
    left: 24,
    right: 24,
    bottom: 34,
    height: 30,
    borderRadius: 30,
    backgroundColor: 'rgba(43, 226, 110, 0.2)',
  },
  chartLabels: {
    flexDirection: 'row',
    justifyContent: 'space-around',
    marginTop: 10,
  },
  chartLabel: {
    color: '#7D8694',
    fontSize: 11,
    fontWeight: '500',
  },
  chartLabelActive: {
    color: '#2BE26E',
    fontSize: 11,
    fontWeight: '700',
  },
  sectionRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-end',
    marginBottom: 10,
  },
  bigSectionTitle: {
    color: '#EFF3FC',
    fontSize: 35,
    fontWeight: '700',
  },
  sectionHint: {
    color: '#97A1B3',
    fontSize: 11,
    letterSpacing: 1.2,
    fontWeight: '700',
  },
  performanceCard: {
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#232B3A',
    backgroundColor: '#171C25',
    paddingHorizontal: 12,
    paddingVertical: 10,
    marginBottom: 10,
  },
  performanceTop: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  performanceLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  performanceIcon: {
    width: 30,
    height: 30,
    borderRadius: 8,
    backgroundColor: '#1D2432',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 8,
  },
  performanceTitle: {
    color: '#EDF2FC',
    fontSize: 16,
    fontWeight: '600',
  },
  performanceRight: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  performanceScore: {
    fontSize: 17,
    fontWeight: '700',
  },
  progressTrack: {
    height: 6,
    borderRadius: 4,
    backgroundColor: '#2A313F',
    overflow: 'hidden',
  },
  progressFill: {
    height: 6,
    borderRadius: 4,
  },
  mentorCard: {
    marginTop: 4,
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#232B3A',
    backgroundColor: '#181E29',
    padding: 14,
    flexDirection: 'row',
    alignItems: 'flex-start',
  },
  mentorBadge: {
    width: 42,
    height: 42,
    borderRadius: 14,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#5A26FF',
    marginRight: 10,
  },
  mentorBody: {
    flex: 1,
  },
  mentorHeader: {
    color: '#AFA4D2',
    fontSize: 15,
    letterSpacing: 1.8,
    fontWeight: '700',
    marginBottom: 8,
  },
  mentorMessage: {
    borderRadius: 10,
    backgroundColor: '#121722',
    padding: 12,
  },
  mentorText: {
    color: '#C7D0DF',
    fontSize: 17,
    lineHeight: 23,
    fontWeight: '500',
  },
  mentorHighlight: {
    color: '#2BE26E',
    fontWeight: '700',
  },
});
