import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#06080D',
  },
  safeArea: {
    flex: 1,
    backgroundColor: '#06080D',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingHorizontal: 18,
    paddingTop: 12,
    paddingBottom: 150,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 16,
  },
  headerLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  headerTitle: {
    color: '#EAF0FC',
    fontSize: 28,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  profileCard: {
    borderRadius: 18,
    borderWidth: 1,
    borderColor: '#202632',
    backgroundColor: '#14181F',
    paddingHorizontal: 16,
    paddingVertical: 16,
    alignItems: 'center',
    marginBottom: 18,
  },
  avatarWrap: {
    width: 110,
    height: 110,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 8,
  },
  avatarGlow: {
    position: 'absolute',
    width: 98,
    height: 98,
    borderRadius: 49,
    backgroundColor: 'rgba(43, 226, 110, 0.2)',
    shadowColor: '#2BE26E',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.6,
    shadowRadius: 14,
    elevation: 6,
  },
  avatar: {
    width: 82,
    height: 82,
    borderRadius: 41,
    borderWidth: 2,
    borderColor: '#E2E7F5',
    backgroundColor: '#303A49',
    alignItems: 'center',
    justifyContent: 'center',
  },
  avatarInitials: {
    color: '#F4F8FF',
    fontSize: 33,
    fontWeight: '700',
  },
  levelBadge: {
    position: 'absolute',
    top: 6,
    right: 6,
    borderRadius: 10,
    paddingHorizontal: 8,
    paddingVertical: 3,
    backgroundColor: '#214F2F',
    borderWidth: 1,
    borderColor: '#3A8B57',
  },
  levelBadgeText: {
    color: '#9FF5C1',
    fontSize: 10,
    fontWeight: '700',
  },
  name: {
    color: '#EEF3FD',
    fontSize: 33,
    fontWeight: '700',
    lineHeight: 36,
  },
  school: {
    marginTop: 4,
    color: '#AAB2C1',
    fontSize: 13,
    fontWeight: '600',
    letterSpacing: 0.4,
  },
  studentId: {
    marginTop: 2,
    color: '#788193',
    fontSize: 13,
    fontWeight: '500',
  },
  statsRow: {
    marginTop: 16,
    width: '100%',
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 10,
  },
  pill: {
    flex: 1,
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#2D3444',
    backgroundColor: '#1B202A',
    minHeight: 44,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
  },
  pillText: {
    color: '#E4EAF6',
    fontSize: 14,
    fontWeight: '600',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: 10,
  },
  sectionTitle: {
    color: '#EEF3FC',
    fontSize: 33,
    fontWeight: '700',
  },
  xpBadge: {
    borderRadius: 10,
    paddingHorizontal: 10,
    paddingVertical: 6,
    backgroundColor: '#3D3314',
    borderWidth: 1,
    borderColor: '#6A5720',
  },
  xpBadgeText: {
    color: '#EBC95C',
    fontSize: 13,
    fontWeight: '700',
  },
  badgeGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'space-between',
    rowGap: 10,
    marginBottom: 18,
  },
  badgeCard: {
    width: '48.5%',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#202632',
    backgroundColor: '#14181F',
    paddingHorizontal: 12,
    paddingVertical: 14,
    alignItems: 'center',
  },
  badgeIconWrap: {
    width: 46,
    height: 46,
    borderRadius: 23,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: 10,
  },
  badgeTitle: {
    color: '#EAF0FA',
    fontSize: 18,
    fontWeight: '600',
    marginBottom: 3,
  },
  badgeSubtitle: {
    color: '#7E8798',
    fontSize: 13,
    fontWeight: '500',
  },
  settingsCard: {
    borderRadius: 16,
    borderWidth: 1,
    borderColor: '#202632',
    backgroundColor: '#14181F',
    paddingHorizontal: 12,
    marginBottom: 18,
  },
  settingsRow: {
    minHeight: 58,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  settingsRowDivider: {
    borderBottomWidth: 1,
    borderBottomColor: '#1E2430',
  },
  settingsLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  settingsIconWrap: {
    width: 32,
    height: 32,
    borderRadius: 9,
    backgroundColor: '#1F2633',
    alignItems: 'center',
    justifyContent: 'center',
  },
  settingsText: {
    color: '#E6ECF7',
    fontSize: 17,
    fontWeight: '500',
  },
  logoutButton: {
    height: 50,
    borderRadius: 25,
    backgroundColor: '#8A51FF',
    borderWidth: 1,
    borderColor: '#C4A8FF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    marginBottom: 12,
  },
  logoutText: {
    color: '#161127',
    fontSize: 20,
    fontWeight: '700',
  },
});
