import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#06080D',
  },
  scroll: {
    flex: 1,
  },
  content: {
    paddingTop: 62,
    paddingHorizontal: 20,
    paddingBottom: 150,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 18,
  },
  backButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#121720',
    borderWidth: 1,
    borderColor: '#1E2633',
  },
  title: {
    flex: 1,
    textAlign: 'center',
    marginLeft: 8,
    color: '#E6ECF8',
    fontSize: 24,
    fontWeight: '700',
  },
  headerActions: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  fileTag: {
    height: 54,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(43, 226, 110, 0.45)',
    backgroundColor: '#11161E',
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    marginBottom: 18,
  },
  fileTagText: {
    marginLeft: 10,
    color: '#D9E1EF',
    fontSize: 14,
    fontWeight: '500',
    flex: 1,
  },
  tabsRow: {
    flexDirection: 'row',
    marginBottom: 20,
  },
  tabItem: {
    marginRight: 18,
    alignItems: 'center',
    flexDirection: 'row',
    paddingBottom: 8,
  },
  tabIcon: {
    marginRight: 4,
  },
  tabLabel: {
    color: '#778091',
    fontSize: 16,
    fontWeight: '500',
  },
  tabLabelActive: {
    color: '#2BE26E',
    fontWeight: '700',
  },
  tabIndicator: {
    position: 'absolute',
    left: 0,
    right: 0,
    bottom: 0,
    height: 3,
    borderRadius: 4,
    backgroundColor: '#2BE26E',
  },
  sectionHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 12,
  },
  sectionTitle: {
    color: '#EEF3FF',
    fontSize: 32,
    fontWeight: '700',
  },
  sectionLink: {
    color: '#2BE26E',
    fontSize: 12,
    letterSpacing: 2,
    fontWeight: '700',
  },
  insightCard: {
    backgroundColor: '#151A23',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#202838',
    marginBottom: 12,
    overflow: 'hidden',
  },
  insightAccent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    width: 3,
    backgroundColor: '#2BE26E',
  },
  insightContent: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    paddingVertical: 14,
    paddingHorizontal: 12,
  },
  insightIconWrap: {
    width: 30,
    height: 30,
    borderRadius: 15,
    backgroundColor: 'rgba(43, 226, 110, 0.14)',
    borderWidth: 1,
    borderColor: 'rgba(43, 226, 110, 0.3)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  insightTextWrap: {
    flex: 1,
  },
  insightTitle: {
    color: '#F1F5FD',
    fontSize: 25,
    fontWeight: '700',
    marginBottom: 4,
  },
  insightBody: {
    color: '#98A2B4',
    fontSize: 15,
    lineHeight: 20,
    fontWeight: '500',
  },
  toolsTitle: {
    color: '#EEF3FF',
    fontSize: 34,
    fontWeight: '700',
    marginTop: 12,
    marginBottom: 12,
  },
  toolCard: {
    backgroundColor: '#1B1F29',
    borderRadius: 14,
    borderWidth: 1,
    borderColor: '#232B3A',
    minHeight: 70,
    marginBottom: 12,
    paddingHorizontal: 14,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  toolCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  toolIconWrap: {
    width: 34,
    height: 34,
    borderRadius: 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 12,
  },
  toolTitle: {
    color: '#EFF3FC',
    fontSize: 22,
    fontWeight: '700',
  },
  toolSubtitle: {
    color: '#9AA3B5',
    fontSize: 14,
    fontWeight: '600',
    marginTop: 2,
  },
  chatFloating: {
    position: 'absolute',
    right: 8,
    bottom: 212,
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatBubble: {
    backgroundColor: '#6D35FF',
    color: '#ECE2FF',
    fontSize: 12,
    borderRadius: 999,
    paddingHorizontal: 10,
    paddingVertical: 6,
    marginRight: 8,
  },
  chatButton: {
    width: 52,
    height: 52,
    borderRadius: 26,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#8E54FF',
    shadowColor: '#8E54FF',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.5,
    shadowRadius: 14,
    elevation: 8,
  },
});
